Fixed consul service errors and added datacenter lookup
trainline/em-scheduler pull request #2
Opened 2018-01-22 11:28 UTC by DavidIHunt

2018-01-22 14:23 UTC, tl-jakecross approved these changes

2018-01-22 18:05 UTC, ghost requested changes

2018-01-22 18:05 UTC, ghost commented on src/services/BlockService.spec.js
> -        it('should fail when not given a key', () => {
@DavidIHunt - This was a test that got deleted. Where is it's replacement?

2018-01-22 18:05 UTC, ghost commented on src/services/BlockService.spec.js
> -        it('should fail when not given a key', () => {
Brutal! 👎

2018-01-25 10:39 UTC, DavidIHunt commented on src/services/BlockService.spec.js
> -        it('should fail when not given a key', () => {
Sorry just seen this... Hasn't been merged yet. Re-evaluating...

2018-01-26 10:26 UTC, merged